package guiAdministradores;

import Comprobantes.ComprobanteSimpeSalida;
import Personas.Usuarios;
import Sedes.SedeCentral;
import Sedes.SedeCiudadColon;
import Sedes.SedePuriscal;
import Sedes.SedeSanPedro;
import guiUsuarios.Inicio;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class HistorialSimpeUsuario extends javax.swing.JFrame {

    int sede;
    String cedulaUser;
    String cedula;
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<ComprobanteSimpeSalida> listaComprobante = new ArrayList<>();

    public HistorialSimpeUsuario() {
        initComponents();
    }

    public HistorialSimpeUsuario(String cedula, int sede, String cedulaUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cedula = cedula;
        this.sede = sede;
        this.cedulaUser = cedulaUser;

        modelo.addColumn("Fecha");
        modelo.addColumn("Monto");

        tablaSimpes.setModel(modelo);

        this.listaComprobante = llenarTabla();
    }

    public ArrayList<ComprobanteSimpeSalida> llenarTabla() {
        ArrayList<ComprobanteSimpeSalida> listaComprobantes = new ArrayList<>();
        switch (this.sede) {
            case 0 -> {
                for (Usuarios u : SedePuriscal.getListaUsers()) {
                    if (u.getCedula().equals(this.cedulaUser)) {
                        listaComprobantes = u.getComprobantesSimpeSalida();
                    }
                }
            }
            case 1 -> {
                for (Usuarios u : SedeSanPedro.getListaUsers()) {
                    if (u.getCedula().equals(this.cedulaUser)) {
                        listaComprobantes = u.getComprobantesSimpeSalida();
                    }
                }
            }
            case 2 -> {
                for (Usuarios u : SedeCiudadColon.getListaUsers()) {
                    if (u.getCedula().equals(this.cedulaUser)) {
                        listaComprobantes = u.getComprobantesSimpeSalida();
                    }
                }
            }
        }

        for (ComprobanteSimpeSalida i : listaComprobantes) {
            modelo.addRow(new Object[]{i.getFecha() + " " + i.getHora(), i.getMonto()});
        }
        return listaComprobantes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVisible = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSimpes = new javax.swing.JTable();
        panelComprobanteTransaccion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jblFechaPago = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jblMontoDebitado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblRealizadoPor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jblMontoAcreditado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jblNumeroMonedero = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jblDestinatario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jblMontoTransferencia = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jblDetalle = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        jblAtras = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        itemBienvenida = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemIrInicio = new javax.swing.JMenuItem();
        menuGestionUsuarios = new javax.swing.JMenu();
        menuBloqueoDesbloqueo = new javax.swing.JMenu();
        itemSolicitudesDesbloqueo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemBloquearCuenta = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemDesbloquearCuenta = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        itemEliminarUsuario = new javax.swing.JMenuItem();
        menuInformacionSedes = new javax.swing.JMenu();
        itemSedePuriscal = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemSedeSanPedro = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemSedeCiudadColon = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelVisible.setBackground(new java.awt.Color(255, 255, 255));

        background.setBackground(new java.awt.Color(252, 247, 215));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaSimpes.setBackground(new java.awt.Color(204, 204, 204));
        tablaSimpes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaSimpes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaSimpesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaSimpes);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 620));

        panelComprobanteTransaccion.setBackground(new java.awt.Color(255, 255, 255));
        panelComprobanteTransaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transferencia BNBUU SIMPE");
        panelComprobanteTransaccion.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 360, 40));

        jSeparator6.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 630, 10));

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 630, 10));

        jSeparator8.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 630, 10));

        jSeparator9.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, 630, 10));

        jSeparator10.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 630, 10));

        jSeparator11.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 630, 10));

        jSeparator12.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 630, 10));

        jSeparator13.setForeground(new java.awt.Color(51, 51, 51));
        panelComprobanteTransaccion.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 630, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Fecha del pago:");
        panelComprobanteTransaccion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 620, -1));

        jblFechaPago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFechaPago.setForeground(new java.awt.Color(51, 51, 51));
        jblFechaPago.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblFechaPago.setText("dd-mm-yy  hh:mm:ss");
        panelComprobanteTransaccion.add(jblFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 620, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Monto debitado");
        panelComprobanteTransaccion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 620, -1));

        jblMontoDebitado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblMontoDebitado.setForeground(new java.awt.Color(51, 51, 51));
        jblMontoDebitado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblMontoDebitado.setText("000000000 Colones");
        panelComprobanteTransaccion.add(jblMontoDebitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 620, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Realizado por:");
        panelComprobanteTransaccion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 620, -1));

        jblRealizadoPor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblRealizadoPor.setForeground(new java.awt.Color(51, 51, 51));
        jblRealizadoPor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblRealizadoPor.setText("Nombre");
        panelComprobanteTransaccion.add(jblRealizadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 620, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Monto acreditado:");
        panelComprobanteTransaccion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 620, -1));

        jblMontoAcreditado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblMontoAcreditado.setForeground(new java.awt.Color(51, 51, 51));
        jblMontoAcreditado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblMontoAcreditado.setText("Monto acreditado");
        panelComprobanteTransaccion.add(jblMontoAcreditado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 620, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Numero de monedero:");
        panelComprobanteTransaccion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 620, -1));

        jblNumeroMonedero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNumeroMonedero.setForeground(new java.awt.Color(51, 51, 51));
        jblNumeroMonedero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblNumeroMonedero.setText("000000000 Colones");
        panelComprobanteTransaccion.add(jblNumeroMonedero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 620, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Destinatario:");
        panelComprobanteTransaccion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 620, -1));

        jblDestinatario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDestinatario.setForeground(new java.awt.Color(51, 51, 51));
        jblDestinatario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblDestinatario.setText("Destinatario");
        panelComprobanteTransaccion.add(jblDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 620, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Monto transferencia");
        panelComprobanteTransaccion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 620, -1));

        jblMontoTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblMontoTransferencia.setForeground(new java.awt.Color(51, 51, 51));
        jblMontoTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblMontoTransferencia.setText("000000000 Colones");
        panelComprobanteTransaccion.add(jblMontoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 620, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Detalle:");
        panelComprobanteTransaccion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jblDetalle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDetalle.setForeground(new java.awt.Color(51, 51, 51));
        jblDetalle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblDetalle.setText("Texto del detalle");
        panelComprobanteTransaccion.add(jblDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 620, -1));

        panelAtras.setBackground(new java.awt.Color(255, 255, 255));
        panelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAtrasMouseExited(evt);
            }
        });
        panelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        panelAtras.add(jblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        panelComprobanteTransaccion.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 60, 40));

        background.add(panelComprobanteTransaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 670, 620));

        javax.swing.GroupLayout panelVisibleLayout = new javax.swing.GroupLayout(panelVisible);
        panelVisible.setLayout(panelVisibleLayout);
        panelVisibleLayout.setHorizontalGroup(
            panelVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        panelVisibleLayout.setVerticalGroup(
            panelVisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));
        barraMenu.setBorder(null);
        barraMenu.setForeground(new java.awt.Color(51, 51, 51));

        menuInicio.setText("Inicio");

        itemBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBienvenida.setText("Bienvenida");
        itemBienvenida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBienvenidaActionPerformed(evt);
            }
        });
        menuInicio.add(itemBienvenida);
        menuInicio.add(jSeparator1);

        itemIrInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemIrInicio.setText("Ir a Inicio");
        itemIrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIrInicioActionPerformed(evt);
            }
        });
        menuInicio.add(itemIrInicio);

        barraMenu.add(menuInicio);

        menuGestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        menuGestionUsuarios.setText("Gestion usuarios y cuentas");
        menuGestionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuBloqueoDesbloqueo.setText("Bloqueos y desbloqueos");
        menuBloqueoDesbloqueo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        itemSolicitudesDesbloqueo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSolicitudesDesbloqueo.setText("Solicitudes debloqueo cuenta");
        itemSolicitudesDesbloqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSolicitudesDesbloqueoActionPerformed(evt);
            }
        });
        menuBloqueoDesbloqueo.add(itemSolicitudesDesbloqueo);
        menuBloqueoDesbloqueo.add(jSeparator2);

        itemBloquearCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBloquearCuenta.setText("Bloquear cuenta");
        itemBloquearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBloquearCuentaActionPerformed(evt);
            }
        });
        menuBloqueoDesbloqueo.add(itemBloquearCuenta);
        menuBloqueoDesbloqueo.add(jSeparator5);

        itemDesbloquearCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemDesbloquearCuenta.setText("Desbloquear cuenta");
        itemDesbloquearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDesbloquearCuentaActionPerformed(evt);
            }
        });
        menuBloqueoDesbloqueo.add(itemDesbloquearCuenta);

        menuGestionUsuarios.add(menuBloqueoDesbloqueo);
        menuGestionUsuarios.add(jSeparator14);

        itemEliminarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemEliminarUsuario.setText("Eliminar usuario");
        itemEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarUsuarioActionPerformed(evt);
            }
        });
        menuGestionUsuarios.add(itemEliminarUsuario);

        barraMenu.add(menuGestionUsuarios);

        menuInformacionSedes.setText("Informacion sedes");

        itemSedePuriscal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSedePuriscal.setText("Sede Puriscal");
        itemSedePuriscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSedePuriscalActionPerformed(evt);
            }
        });
        menuInformacionSedes.add(itemSedePuriscal);
        menuInformacionSedes.add(jSeparator3);

        itemSedeSanPedro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSedeSanPedro.setText("Sede San Pedro");
        itemSedeSanPedro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSedeSanPedroActionPerformed(evt);
            }
        });
        menuInformacionSedes.add(itemSedeSanPedro);
        menuInformacionSedes.add(jSeparator4);

        itemSedeCiudadColon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemSedeCiudadColon.setText("Sede Ciudad Colon");
        itemSedeCiudadColon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSedeCiudadColonActionPerformed(evt);
            }
        });
        menuInformacionSedes.add(itemSedeCiudadColon);

        barraMenu.add(menuInformacionSedes);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBienvenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBienvenidaActionPerformed
        PrincipalAdmins admins = new PrincipalAdmins(cedula);
        admins.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemBienvenidaActionPerformed

    private void itemIrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIrInicioActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemIrInicioActionPerformed

    private void itemSolicitudesDesbloqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSolicitudesDesbloqueoActionPerformed
        SolicitudesDesbloqueo soli = new SolicitudesDesbloqueo(this.cedula);
        soli.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSolicitudesDesbloqueoActionPerformed

    private void itemBloquearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBloquearCuentaActionPerformed
        BloquearCuenta bloquear = new BloquearCuenta(this.cedula);
        bloquear.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemBloquearCuentaActionPerformed

    private void itemDesbloquearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDesbloquearCuentaActionPerformed
        DesbloquearCuenta desbloquear = new DesbloquearCuenta(this.cedula);
        desbloquear.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemDesbloquearCuentaActionPerformed

    private void itemSedePuriscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSedePuriscalActionPerformed
        GestionSedes gestion = new GestionSedes(0, this.cedula);
        gestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSedePuriscalActionPerformed

    private void itemSedeSanPedroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSedeSanPedroActionPerformed
        GestionSedes gestion = new GestionSedes(1, this.cedula);
        gestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSedeSanPedroActionPerformed

    private void itemSedeCiudadColonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSedeCiudadColonActionPerformed
        GestionSedes gestion = new GestionSedes(2, this.cedula);
        gestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSedeCiudadColonActionPerformed

    private void tablaSimpesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSimpesMousePressed
        if (tablaSimpes.getSelectedRow() >= 0) {

            int filaSeleccionada = tablaSimpes.getSelectedRow();
            ComprobanteSimpeSalida comprobante = this.listaComprobante.get(filaSeleccionada);

            String realizadoPor = "";
            String destinatario = "";
            String detalle = comprobante.getDetalle();
            if (detalle.equals("Ingrese el detalle")) {
                detalle = "ninguno";
            }

            for (Usuarios i : SedeCentral.getListaUsers()) {
                if (i.getTelefono().equals(comprobante.getNumeroEmisor())) {
                    realizadoPor = i.getApellidos() + " " + i.getUsuario();
                }

                if (i.getTelefono().equals(comprobante.getNumeroReceptor())) {
                    destinatario = i.getApellidos() + " " + i.getUsuario();
                }
            }

            jblFechaPago.setText(comprobante.getFecha() + " " + comprobante.getHora());
            jblMontoDebitado.setText(String.valueOf(comprobante.getMonto()) + " Colones");
            jblRealizadoPor.setText(realizadoPor);
            jblMontoAcreditado.setText(String.valueOf(comprobante.getMonto()) + " Colones");
            jblNumeroMonedero.setText(comprobante.getNumeroReceptor());
            jblDestinatario.setText(destinatario);
            jblMontoTransferencia.setText(String.valueOf(comprobante.getMonto()) + " Colones");
            jblDetalle.setText(detalle);
        }
    }//GEN-LAST:event_tablaSimpesMousePressed

    private void panelAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseEntered
        panelAtras.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_panelAtrasMouseEntered

    private void panelAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseExited
        panelAtras.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_panelAtrasMouseExited

    private void panelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAtrasMouseClicked
        VerInfoUsuario info = new VerInfoUsuario(this.cedula, this.sede, this.cedulaUser);
        info.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelAtrasMouseClicked

    private void itemEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarUsuarioActionPerformed
        EliminarUsuario eliminar = new EliminarUsuario(this.cedula);
        eliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemEliminarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialSimpeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialSimpeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialSimpeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialSimpeUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialSimpeUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemBienvenida;
    private javax.swing.JMenuItem itemBloquearCuenta;
    private javax.swing.JMenuItem itemDesbloquearCuenta;
    private javax.swing.JMenuItem itemEliminarUsuario;
    private javax.swing.JMenuItem itemIrInicio;
    private javax.swing.JMenuItem itemSedeCiudadColon;
    private javax.swing.JMenuItem itemSedePuriscal;
    javax.swing.JMenuItem itemSedeSanPedro;
    private javax.swing.JMenuItem itemSolicitudesDesbloqueo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel jblAtras;
    private javax.swing.JLabel jblDestinatario;
    private javax.swing.JLabel jblDetalle;
    private javax.swing.JLabel jblFechaPago;
    private javax.swing.JLabel jblMontoAcreditado;
    private javax.swing.JLabel jblMontoDebitado;
    private javax.swing.JLabel jblMontoTransferencia;
    private javax.swing.JLabel jblNumeroMonedero;
    private javax.swing.JLabel jblRealizadoPor;
    private javax.swing.JMenu menuBloqueoDesbloqueo;
    private javax.swing.JMenu menuGestionUsuarios;
    private javax.swing.JMenu menuInformacionSedes;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelComprobanteTransaccion;
    private javax.swing.JPanel panelVisible;
    private javax.swing.JTable tablaSimpes;
    // End of variables declaration//GEN-END:variables
}
