package guiUsuarios;

import Personas.Usuarios;
import Sedes.SedeCentral;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Depositar extends javax.swing.JFrame {

    String cedula;
    int sede;
    boolean verPassword;
    String cuentaElegida;

    public Depositar() {
        initComponents();
    }

    public Depositar(String cedula, int sede) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cedula = cedula;
        this.sede = sede;
        this.verPassword = false;
        alertaClave.setVisible(false);
        jblAlerta.setVisible(false);
        txtsPorDefecto();
        panelDepositarBarra.setBackground(new Color(232, 225, 182));
        
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                jblNombrePerfil.setText(i.getUsuario() + " " + i.getApellidos());
                switch (this.sede) {
                    case 0 -> {
                        jblVentanaActual.setText("Sede Puriscal");
                    }
                    case 1 -> {
                        jblVentanaActual.setText("Sede San Pedro");
                    }
                    case 2 -> { 
                        jblVentanaActual.setText("Sede Ciudad Colon");
                    }
                }
            }
        }
    }

    public void txtsPorDefecto() {
        txtClaveNum.setText("Ingrese su clave");
        psdPassword.setText("Ingrese su password");
    }

    public boolean MontoMaximaAlcanzado(String num) {
        boolean maximoAlcanzado = false;
        try {
            if (Double.parseDouble(jblMontoDeposito.getText() + num) > 10000000) {
                maximoAlcanzado = true;
                JOptionPane.showMessageDialog(null, "Monto max 10 000 000");
            }
        } catch (Exception e) {
        }
        return maximoAlcanzado;
    }

    public boolean DigitosMaxAlcanzados(String num) {
        boolean digitosMaximos = false;
        if ((jblMontoDeposito.getText() + num).length() > 10) {
            digitosMaximos = true;
            JOptionPane.showMessageDialog(null, "Maximo de digitos alcanzado");
        }
        return digitosMaximos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jblNombreBanco = new javax.swing.JLabel();
        jblPerfil = new javax.swing.JLabel();
        iconBarra = new javax.swing.JLabel();
        jblNombrePerfil = new javax.swing.JLabel();
        jblVentanaActual = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        jblAtras = new javax.swing.JLabel();
        jblBarra = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        jblSalir = new javax.swing.JLabel();
        panelConfig = new javax.swing.JPanel();
        jblConfig = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        jblFondoPerfil = new javax.swing.JLabel();
        panelDepositarBarra = new javax.swing.JPanel();
        jblDepositar = new javax.swing.JLabel();
        panelRetirarBarra = new javax.swing.JPanel();
        jblRetirar = new javax.swing.JLabel();
        panelVerSaldoBarra = new javax.swing.JPanel();
        javax.swing.JLabel jblVerSaldo = new javax.swing.JLabel();
        panelDashboardBarra = new javax.swing.JPanel();
        jblDashboard = new javax.swing.JLabel();
        panelHabilitarCuentasBarra = new javax.swing.JPanel();
        jblHabilitarCuentas = new javax.swing.JLabel();
        panelComentariosBarra = new javax.swing.JPanel();
        jblComentarios = new javax.swing.JLabel();
        panelSimpeBarra = new javax.swing.JPanel();
        jblSimpe = new javax.swing.JLabel();
        pizarra = new javax.swing.JTabbedPane();
        panelValidar = new javax.swing.JPanel();
        jblClaveNum = new javax.swing.JLabel();
        txtClaveNum = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jblPassword = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        panelVerPassword = new javax.swing.JPanel();
        jblVerPassword = new javax.swing.JLabel();
        panelContinuar = new javax.swing.JPanel();
        jblContinuar = new javax.swing.JLabel();
        alertaClave = new javax.swing.JLabel();
        jblAlerta = new javax.swing.JLabel();
        jblOpcionActual = new javax.swing.JLabel();
        panelElegir = new javax.swing.JPanel();
        jblOpcionActual1 = new javax.swing.JLabel();
        panelCuentaCorriente = new javax.swing.JPanel();
        jblCuentaCorriente = new javax.swing.JLabel();
        panelCuentaAhorro = new javax.swing.JPanel();
        jblCuentaAhorro = new javax.swing.JLabel();
        panelCuentaSimpe = new javax.swing.JPanel();
        jblCuentaSimpe = new javax.swing.JLabel();
        jblInformativo = new javax.swing.JLabel();
        panelDeposito = new javax.swing.JPanel();
        jblInformativoDep = new javax.swing.JLabel();
        panelNumerico = new javax.swing.JPanel();
        panelNum1 = new javax.swing.JPanel();
        uno = new javax.swing.JLabel();
        panelNum2 = new javax.swing.JPanel();
        dos = new javax.swing.JLabel();
        panelNum3 = new javax.swing.JPanel();
        tres = new javax.swing.JLabel();
        panelNum4 = new javax.swing.JPanel();
        cuatro = new javax.swing.JLabel();
        panelNum5 = new javax.swing.JPanel();
        cinco = new javax.swing.JLabel();
        panelNum6 = new javax.swing.JPanel();
        seis = new javax.swing.JLabel();
        panelNum7 = new javax.swing.JPanel();
        siete = new javax.swing.JLabel();
        panelNum8 = new javax.swing.JPanel();
        ocho = new javax.swing.JLabel();
        panelNum9 = new javax.swing.JPanel();
        nueve = new javax.swing.JLabel();
        panelNum0 = new javax.swing.JPanel();
        cero = new javax.swing.JLabel();
        panelPunto = new javax.swing.JPanel();
        punto = new javax.swing.JLabel();
        panelNum00 = new javax.swing.JPanel();
        dobleCero = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        cancelar = new javax.swing.JLabel();
        panelCorreccion = new javax.swing.JPanel();
        correccion = new javax.swing.JLabel();
        panelAceptar = new javax.swing.JPanel();
        aceptar = new javax.swing.JLabel();
        tocar = new javax.swing.JLabel();
        panelMontoDeposito = new javax.swing.JPanel();
        jblMontoDeposito = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblNombreBanco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblNombreBanco.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco.setText("BNBUU");
        background.add(jblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 120, 70));

        jblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfilNegro128px.png"))); // NOI18N
        background.add(jblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 130));

        iconBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo32px.png"))); // NOI18N
        background.add(iconBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 70));

        jblNombrePerfil.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jblNombrePerfil.setForeground(new java.awt.Color(51, 51, 51));
        jblNombrePerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombrePerfil.setText("Nombre");
        background.add(jblNombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, -1));

        jblVentanaActual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblVentanaActual.setForeground(new java.awt.Color(51, 51, 51));
        jblVentanaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubicacion32px.png"))); // NOI18N
        jblVentanaActual.setText("Ubicacion");
        background.add(jblVentanaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 320, 70));

        panelAtras.setBackground(new java.awt.Color(210, 196, 103));
        panelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblAtrasMouseExited(evt);
            }
        });
        panelAtras.add(jblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 50, 50));

        jblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BarraColorBambu.png"))); // NOI18N
        background.add(jblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 790, 70));

        panelSalir.setBackground(new java.awt.Color(247, 240, 194));
        panelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida32px.png"))); // NOI18N
        jblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblSalirMouseExited(evt);
            }
        });
        panelSalir.add(jblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        panelConfig.setBackground(new java.awt.Color(247, 240, 194));
        panelConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config32px.png"))); // NOI18N
        jblConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblConfigMouseExited(evt);
            }
        });
        panelConfig.add(jblConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 50));

        panelOpciones.setBackground(new java.awt.Color(252, 247, 215));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblFondoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFondoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuadroFondoPerfil2.png"))); // NOI18N
        panelOpciones.add(jblFondoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        panelDepositarBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelDepositarBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDepositar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDepositar.setForeground(new java.awt.Color(102, 102, 102));
        jblDepositar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDepositar.setText("Depositar");
        jblDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDepositarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDepositarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDepositarMouseExited(evt);
            }
        });
        panelDepositarBarra.add(jblDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelDepositarBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 60));

        panelRetirarBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelRetirarBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblRetirar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblRetirar.setForeground(new java.awt.Color(102, 102, 102));
        jblRetirar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblRetirar.setText("Retirar");
        jblRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblRetirarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblRetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblRetirarMouseExited(evt);
            }
        });
        panelRetirarBarra.add(jblRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelRetirarBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 60));

        panelVerSaldoBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelVerSaldoBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblVerSaldo.setForeground(new java.awt.Color(102, 102, 102));
        jblVerSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerSaldo.setText("Ver saldo");
        jblVerSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseExited(evt);
            }
        });
        panelVerSaldoBarra.add(jblVerSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelVerSaldoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 60));

        panelDashboardBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelDashboardBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDashboard.setForeground(new java.awt.Color(102, 102, 102));
        jblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDashboard.setText("Dashboard");
        jblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDashboardMouseExited(evt);
            }
        });
        panelDashboardBarra.add(jblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelDashboardBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 60));

        panelHabilitarCuentasBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelHabilitarCuentasBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblHabilitarCuentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblHabilitarCuentas.setForeground(new java.awt.Color(102, 102, 102));
        jblHabilitarCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblHabilitarCuentas.setText("Habilitar Cuentas");
        jblHabilitarCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblHabilitarCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseExited(evt);
            }
        });
        panelHabilitarCuentasBarra.add(jblHabilitarCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelHabilitarCuentasBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 60));

        panelComentariosBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelComentariosBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblComentarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblComentarios.setForeground(new java.awt.Color(102, 102, 102));
        jblComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblComentarios.setText("Comentarios");
        jblComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblComentariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblComentariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblComentariosMouseExited(evt);
            }
        });
        panelComentariosBarra.add(jblComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelComentariosBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 60));

        panelSimpeBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelSimpeBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblSimpe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblSimpe.setForeground(new java.awt.Color(102, 102, 102));
        jblSimpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSimpe.setText("Simpe");
        jblSimpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblSimpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSimpeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblSimpeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblSimpeMouseExited(evt);
            }
        });
        panelSimpeBarra.add(jblSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelSimpeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 60));

        background.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        pizarra.setBackground(new java.awt.Color(204, 204, 204));
        pizarra.setForeground(new java.awt.Color(102, 102, 102));

        panelValidar.setBackground(new java.awt.Color(255, 255, 255));
        panelValidar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblClaveNum.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblClaveNum.setForeground(new java.awt.Color(51, 51, 51));
        jblClaveNum.setText("CLAVE NUMERICA");
        panelValidar.add(jblClaveNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtClaveNum.setBackground(new java.awt.Color(255, 255, 255));
        txtClaveNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtClaveNum.setForeground(new java.awt.Color(204, 204, 204));
        txtClaveNum.setText("Ingrese su clave");
        txtClaveNum.setBorder(null);
        txtClaveNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtClaveNumMousePressed(evt);
            }
        });
        txtClaveNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveNumKeyTyped(evt);
            }
        });
        panelValidar.add(txtClaveNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, 50));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        panelValidar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 530, 10));

        jblPassword.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        panelValidar.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("Ingrese su password");
        psdPassword.setBorder(null);
        psdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordMousePressed(evt);
            }
        });
        panelValidar.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 380, 60));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        panelValidar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 530, 10));

        panelVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseExited(evt);
            }
        });
        panelVerPassword.add(jblVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelValidar.add(panelVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 40, 40));

        panelContinuar.setBackground(new java.awt.Color(92, 88, 29));
        panelContinuar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblContinuar.setBackground(new java.awt.Color(92, 88, 29));
        jblContinuar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblContinuar.setText("CONTINUAR");
        jblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblContinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblContinuarMouseExited(evt);
            }
        });
        panelContinuar.add(jblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelValidar.add(panelContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 170, 70));

        alertaClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertaClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/advertencia.png"))); // NOI18N
        panelValidar.add(alertaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 40, 40));

        jblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblAlerta.setForeground(new java.awt.Color(255, 102, 102));
        jblAlerta.setText("Solo numeros");
        panelValidar.add(jblAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 185, 250, -1));

        jblOpcionActual.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblOpcionActual.setForeground(new java.awt.Color(51, 51, 51));
        jblOpcionActual.setText("DEPOSITAR");
        panelValidar.add(jblOpcionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 220, 40));

        pizarra.addTab("Validar", panelValidar);

        panelElegir.setBackground(new java.awt.Color(255, 255, 255));
        panelElegir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblOpcionActual1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblOpcionActual1.setForeground(new java.awt.Color(51, 51, 51));
        jblOpcionActual1.setText("DEPOSITAR");
        panelElegir.add(jblOpcionActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 220, 40));

        panelCuentaCorriente.setBackground(new java.awt.Color(92, 88, 29));
        panelCuentaCorriente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCuentaCorriente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblCuentaCorriente.setForeground(new java.awt.Color(255, 255, 255));
        jblCuentaCorriente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCuentaCorriente.setText("Cuenta corriente");
        jblCuentaCorriente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblCuentaCorriente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCuentaCorrienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblCuentaCorrienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblCuentaCorrienteMouseExited(evt);
            }
        });
        panelCuentaCorriente.add(jblCuentaCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        panelElegir.add(panelCuentaCorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 460, 70));

        panelCuentaAhorro.setBackground(new java.awt.Color(92, 88, 29));
        panelCuentaAhorro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCuentaAhorro.setBackground(new java.awt.Color(0, 0, 0));
        jblCuentaAhorro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblCuentaAhorro.setForeground(new java.awt.Color(255, 255, 255));
        jblCuentaAhorro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCuentaAhorro.setText("Cuenta ahorro");
        jblCuentaAhorro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblCuentaAhorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseExited(evt);
            }
        });
        panelCuentaAhorro.add(jblCuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        panelElegir.add(panelCuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 460, 70));

        panelCuentaSimpe.setBackground(new java.awt.Color(92, 88, 29));
        panelCuentaSimpe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCuentaSimpe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblCuentaSimpe.setForeground(new java.awt.Color(255, 255, 255));
        jblCuentaSimpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCuentaSimpe.setText("Cuenta simpe");
        jblCuentaSimpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblCuentaSimpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseExited(evt);
            }
        });
        panelCuentaSimpe.add(jblCuentaSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        panelElegir.add(panelCuentaSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 460, 70));

        jblInformativo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblInformativo.setForeground(new java.awt.Color(51, 51, 51));
        jblInformativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblInformativo.setText("Elige la cuenta para el tramite");
        panelElegir.add(jblInformativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 550, 60));

        pizarra.addTab("Elegir", panelElegir);

        panelDeposito.setBackground(new java.awt.Color(255, 255, 255));
        panelDeposito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblInformativoDep.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jblInformativoDep.setForeground(new java.awt.Color(51, 51, 51));
        jblInformativoDep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblInformativoDep.setText("Ingresa el monto de deposito");
        panelDeposito.add(jblInformativoDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 790, 60));

        panelNumerico.setBackground(new java.awt.Color(204, 204, 204));
        panelNumerico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNum1.setBackground(new java.awt.Color(153, 153, 153));
        panelNum1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        uno.setForeground(new java.awt.Color(51, 51, 51));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uno.setText("1");
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unoMousePressed(evt);
            }
        });
        panelNum1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 80));

        panelNum2.setBackground(new java.awt.Color(153, 153, 153));
        panelNum2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dos.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        dos.setForeground(new java.awt.Color(51, 51, 51));
        dos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dos.setText("2");
        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dosMousePressed(evt);
            }
        });
        panelNum2.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 80));

        panelNum3.setBackground(new java.awt.Color(153, 153, 153));
        panelNum3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tres.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        tres.setForeground(new java.awt.Color(51, 51, 51));
        tres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tres.setText("3");
        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tresMousePressed(evt);
            }
        });
        panelNum3.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, 80));

        panelNum4.setBackground(new java.awt.Color(153, 153, 153));
        panelNum4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuatro.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        cuatro.setForeground(new java.awt.Color(51, 51, 51));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuatro.setText("4");
        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cuatroMousePressed(evt);
            }
        });
        panelNum4.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 80));

        panelNum5.setBackground(new java.awt.Color(153, 153, 153));
        panelNum5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cinco.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        cinco.setForeground(new java.awt.Color(51, 51, 51));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cinco.setText("5");
        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cincoMousePressed(evt);
            }
        });
        panelNum5.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 90, 80));

        panelNum6.setBackground(new java.awt.Color(153, 153, 153));
        panelNum6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seis.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        seis.setForeground(new java.awt.Color(51, 51, 51));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seis.setText("6");
        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seisMousePressed(evt);
            }
        });
        panelNum6.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 90, 80));

        panelNum7.setBackground(new java.awt.Color(153, 153, 153));
        panelNum7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        siete.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        siete.setForeground(new java.awt.Color(51, 51, 51));
        siete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siete.setText("7");
        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sieteMousePressed(evt);
            }
        });
        panelNum7.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 80));

        panelNum8.setBackground(new java.awt.Color(153, 153, 153));
        panelNum8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ocho.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        ocho.setForeground(new java.awt.Color(51, 51, 51));
        ocho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ocho.setText("8");
        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ochoMousePressed(evt);
            }
        });
        panelNum8.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 80));

        panelNum9.setBackground(new java.awt.Color(153, 153, 153));
        panelNum9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nueve.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        nueve.setForeground(new java.awt.Color(51, 51, 51));
        nueve.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nueve.setText("9");
        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nueveMousePressed(evt);
            }
        });
        panelNum9.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 90, 80));

        panelNum0.setBackground(new java.awt.Color(153, 153, 153));
        panelNum0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cero.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        cero.setForeground(new java.awt.Color(51, 51, 51));
        cero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cero.setText("0");
        cero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ceroMousePressed(evt);
            }
        });
        panelNum0.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 80));

        panelPunto.setBackground(new java.awt.Color(153, 153, 153));
        panelPunto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        punto.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        punto.setForeground(new java.awt.Color(51, 51, 51));
        punto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        punto.setText(".");
        punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        punto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                puntoMousePressed(evt);
            }
        });
        panelPunto.add(punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 90, 80));

        panelNum00.setBackground(new java.awt.Color(153, 153, 153));
        panelNum00.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dobleCero.setFont(new java.awt.Font("Segoe UI", 1, 55)); // NOI18N
        dobleCero.setForeground(new java.awt.Color(51, 51, 51));
        dobleCero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dobleCero.setText("00");
        dobleCero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dobleCero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dobleCeroMousePressed(evt);
            }
        });
        panelNum00.add(dobleCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 80));

        panelNumerico.add(panelNum00, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 90, 80));

        panelCancelar.setBackground(new java.awt.Color(153, 153, 153));
        panelCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(51, 51, 51));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarCajero.png"))); // NOI18N
        cancelar.setText("CANCEL");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarMousePressed(evt);
            }
        });
        panelCancelar.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        panelNumerico.add(panelCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 180, 50));

        panelCorreccion.setBackground(new java.awt.Color(153, 153, 153));
        panelCorreccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correccion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        correccion.setForeground(new java.awt.Color(51, 51, 51));
        correccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        correccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/correctionCajero.png"))); // NOI18N
        correccion.setText("CORRECCION");
        correccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        correccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correccionMousePressed(evt);
            }
        });
        panelCorreccion.add(correccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        panelNumerico.add(panelCorreccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 180, 50));

        panelAceptar.setBackground(new java.awt.Color(153, 153, 153));
        panelAceptar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        aceptar.setForeground(new java.awt.Color(51, 51, 51));
        aceptar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aceptarCajero.png"))); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aceptarMousePressed(evt);
            }
        });
        panelAceptar.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 50));

        panelNumerico.add(panelAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 180, 50));

        tocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tocar128px.png"))); // NOI18N
        panelNumerico.add(tocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        panelDeposito.add(panelNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 610, 420));

        panelMontoDeposito.setBackground(new java.awt.Color(204, 204, 204));
        panelMontoDeposito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblMontoDeposito.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jblMontoDeposito.setForeground(new java.awt.Color(51, 51, 51));
        jblMontoDeposito.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblMontoDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colon55px.png"))); // NOI18N
        jblMontoDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMontoDeposito.add(jblMontoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        panelDeposito.add(panelMontoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 390, 70));

        pizarra.addTab("Depositar", panelDeposito);

        background.add(pizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 790, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseClicked
        switch (pizarra.getSelectedIndex()) {
            case 0 -> {
                PrincipalUsers users = new PrincipalUsers(this.cedula, this.sede);
                users.setVisible(true);
                panelDepositarBarra.setBackground(new Color(252, 247, 215));
                this.dispose();
            }
            case 1 -> {
                pizarra.setSelectedIndex(0);
                txtsPorDefecto();
            }
            case 2 -> {
                pizarra.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_jblAtrasMouseClicked

    private void jblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseEntered
        panelAtras.setBackground(new Color(245, 228, 120));
    }//GEN-LAST:event_jblAtrasMouseEntered

    private void jblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseExited
        panelAtras.setBackground(new Color(210, 196, 103));
    }//GEN-LAST:event_jblAtrasMouseExited

    private void jblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseClicked
        Inicio ini = new Inicio();
        ini.setVisible(true);
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblSalirMouseClicked

    private void jblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseEntered
        panelSalir.setBackground(new Color(255, 255, 218));
    }//GEN-LAST:event_jblSalirMouseEntered

    private void jblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseExited
        panelSalir.setBackground(new Color(247, 240, 194));
    }//GEN-LAST:event_jblSalirMouseExited

    private void jblDepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseClicked

    }//GEN-LAST:event_jblDepositarMouseClicked

    private void jblDepositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseEntered
        //panelDepositarBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDepositarMouseEntered

    private void jblDepositarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseExited
        //panelDepositarBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDepositarMouseExited

    private void jblRetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseClicked
        Retirar retirar = new Retirar(this.cedula, this.sede);
        retirar.setVisible(true);
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblRetirarMouseClicked

    private void jblRetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseEntered
        panelRetirarBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblRetirarMouseEntered

    private void jblRetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseExited
        panelRetirarBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblRetirarMouseExited

    private void jblVerSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseClicked
        VerSaldo ver = new VerSaldo(this.cedula, this.sede);
        ver.setVisible(true);
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblVerSaldoMouseClicked

    private void jblVerSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseEntered
        panelVerSaldoBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblVerSaldoMouseEntered

    private void jblVerSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseExited
        panelVerSaldoBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblVerSaldoMouseExited

    private void jblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseClicked
        PrincipalUsers users = new PrincipalUsers(this.cedula, this.sede);
        users.setVisible(true);
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblDashboardMouseClicked

    private void jblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseEntered
        panelDashboardBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDashboardMouseEntered

    private void jblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseExited
        panelDashboardBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDashboardMouseExited

    private void jblHabilitarCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseClicked
        HabilitarCuentas habilitar = new HabilitarCuentas(this.cedula, this.sede);
        habilitar.setVisible(true);
        //panelDashboardBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblHabilitarCuentasMouseClicked

    private void jblHabilitarCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseEntered
        panelHabilitarCuentasBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblHabilitarCuentasMouseEntered

    private void jblHabilitarCuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseExited
        panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblHabilitarCuentasMouseExited

    private void jblComentariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseClicked

    }//GEN-LAST:event_jblComentariosMouseClicked

    private void jblComentariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseEntered
        panelComentariosBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblComentariosMouseEntered

    private void jblComentariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseExited
        panelComentariosBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblComentariosMouseExited

    private void jblConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseClicked
        ConfigurarPerfil config = new ConfigurarPerfil(this.cedula, this.sede);
        config.setVisible(true);
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblConfigMouseClicked

    private void jblConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseEntered
        panelConfig.setBackground(new Color(255, 255, 218));
    }//GEN-LAST:event_jblConfigMouseEntered

    private void jblConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseExited
        panelConfig.setBackground(new Color(247, 240, 194));
    }//GEN-LAST:event_jblConfigMouseExited

    private void txtClaveNumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveNumMousePressed

        String psd = String.valueOf(psdPassword.getPassword());
        if (txtClaveNum.getText().equals("Ingrese su clave")) {
            txtClaveNum.setText("");
        }
        txtClaveNum.setForeground(Color.black);
        if (psd.equals("")) {
            psdPassword.setText("Ingrese su password");
        } else {
            psdPassword.setText(psd);
        }
        psdPassword.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_txtClaveNumMousePressed

    private void psdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordMousePressed

        String user = txtClaveNum.getText();
        if (String.valueOf(psdPassword.getPassword()).equals("Ingrese su password")) {
            psdPassword.setText("");
        }
        psdPassword.setForeground(Color.black);
        if (user.equals("")) {
            txtClaveNum.setText("Ingrese su clave");
        } else {
            txtClaveNum.setText(user);
        }
        txtClaveNum.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_psdPasswordMousePressed

    private void jblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseClicked
        if (verPassword == false) {
            verPassword = true;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');

        }
    }//GEN-LAST:event_jblVerPasswordMouseClicked

    private void jblVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseEntered
        panelVerPassword.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPasswordMouseEntered

    private void jblVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseExited
        panelVerPassword.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPasswordMouseExited

    private void jblContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseClicked
        try {
            for (Usuarios i : SedeCentral.ListaUsers) {
                if (i.getCedula().equals(this.cedula)) {
                    if (Integer.parseInt(txtClaveNum.getText()) == i.getClaveNumerica() && String.valueOf(psdPassword.getPassword()).equals(i.getPassword())) {
                        JOptionPane.showMessageDialog(null, "Datos correctos");
                        pizarra.setSelectedIndex(1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Datos incorrectos");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Rellena todos los espacios");
        }
    }//GEN-LAST:event_jblContinuarMouseClicked

    private void jblContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseEntered
        panelContinuar.setBackground(new Color(153, 145, 86));
        jblContinuar.setForeground(Color.black);
    }//GEN-LAST:event_jblContinuarMouseEntered

    private void jblContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseExited
        panelContinuar.setBackground(new Color(92, 88, 29));
        jblContinuar.setForeground(Color.white);
    }//GEN-LAST:event_jblContinuarMouseExited

    private void txtClaveNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveNumKeyTyped
        char tecla = evt.getKeyChar();
        boolean teclaBorrar = true;
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            teclaBorrar = false;
        }

        if (!Character.isDigit(tecla) && teclaBorrar == false) {

            evt.consume();
            alertaClave.setVisible(true);
            jblAlerta.setVisible(true);
            jblAlerta.setText("Solo numeros");

        } else if (txtClaveNum.getText().length() == 4) {
            evt.consume();
            jblAlerta.setText("Max numeros alcanzado");
            jblAlerta.setVisible(true);
            alertaClave.setVisible(true);
        } else {
            alertaClave.setVisible(false);
            jblAlerta.setVisible(false);
        }
    }//GEN-LAST:event_txtClaveNumKeyTyped

    private void jblCuentaCorrienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaCorrienteMouseEntered
        panelCuentaCorriente.setBackground(new Color(153, 145, 86));
        jblCuentaCorriente.setForeground(Color.black);
    }//GEN-LAST:event_jblCuentaCorrienteMouseEntered

    private void jblCuentaCorrienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaCorrienteMouseExited
        panelCuentaCorriente.setBackground(new Color(92, 88, 29));
        jblCuentaCorriente.setForeground(Color.white);
    }//GEN-LAST:event_jblCuentaCorrienteMouseExited

    private void jblCuentaCorrienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaCorrienteMouseClicked
        this.cuentaElegida = "corriente";
        pizarra.setSelectedIndex(2);
    }//GEN-LAST:event_jblCuentaCorrienteMouseClicked

    private void jblCuentaAhorroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseEntered
        panelCuentaAhorro.setBackground(new Color(153, 145, 86));
        jblCuentaAhorro.setForeground(Color.black);
    }//GEN-LAST:event_jblCuentaAhorroMouseEntered

    private void jblCuentaAhorroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseExited
        panelCuentaAhorro.setBackground(new Color(92, 88, 29));
        jblCuentaAhorro.setForeground(Color.white);
    }//GEN-LAST:event_jblCuentaAhorroMouseExited

    private void jblCuentaAhorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaAhorro().getEstado() == true) {
                    this.cuentaElegida = "ahorro";
                    pizarra.setSelectedIndex(2);
                } else {
                    JOptionPane.showMessageDialog(null, "Cuenta inactiva, debes habilitarla");
                }
            }
        }
    }//GEN-LAST:event_jblCuentaAhorroMouseClicked

    private void jblCuentaSimpeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseEntered
        panelCuentaSimpe.setBackground(new Color(153, 145, 86));
        jblCuentaSimpe.setForeground(Color.black);
    }//GEN-LAST:event_jblCuentaSimpeMouseEntered

    private void jblCuentaSimpeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseExited
        panelCuentaSimpe.setBackground(new Color(92, 88, 29));
        jblCuentaSimpe.setForeground(Color.white);
    }//GEN-LAST:event_jblCuentaSimpeMouseExited

    private void jblCuentaSimpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaSimpe().getEstado() == true) {
                    this.cuentaElegida = "simpe";
                    pizarra.setSelectedIndex(2);
                } else {
                    JOptionPane.showMessageDialog(null, "Cuenta inactiva, debes habilitarla");
                }
            }
        }
    }//GEN-LAST:event_jblCuentaSimpeMouseClicked

    //PANEL NUMERICO

    private void unoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMousePressed
        if (MontoMaximaAlcanzado("1") == false && DigitosMaxAlcanzados("1") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 1);
    }//GEN-LAST:event_unoMousePressed

    private void dosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMousePressed
        if (MontoMaximaAlcanzado("2") == false && DigitosMaxAlcanzados("2") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 2);
    }//GEN-LAST:event_dosMousePressed

    private void tresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMousePressed
        if (MontoMaximaAlcanzado("3") == false && DigitosMaxAlcanzados("3") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 3);
    }//GEN-LAST:event_tresMousePressed

    private void cuatroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMousePressed
        if (MontoMaximaAlcanzado("4") == false && DigitosMaxAlcanzados("4") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 4);
    }//GEN-LAST:event_cuatroMousePressed

    private void cincoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMousePressed
        if (MontoMaximaAlcanzado("5") == false && DigitosMaxAlcanzados("5") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 5);
    }//GEN-LAST:event_cincoMousePressed

    private void seisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMousePressed
        if (MontoMaximaAlcanzado("6") == false && DigitosMaxAlcanzados("6") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 6);
    }//GEN-LAST:event_seisMousePressed

    private void sieteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMousePressed
        if (MontoMaximaAlcanzado("7") == false && DigitosMaxAlcanzados("7") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 7);
    }//GEN-LAST:event_sieteMousePressed

    private void ochoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMousePressed
        if (MontoMaximaAlcanzado("8") == false && DigitosMaxAlcanzados("8") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 8);
    }//GEN-LAST:event_ochoMousePressed

    private void nueveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMousePressed
        if (MontoMaximaAlcanzado("9") == false && DigitosMaxAlcanzados("9") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 9);
    }//GEN-LAST:event_nueveMousePressed

    private void ceroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMousePressed
        if (MontoMaximaAlcanzado("0") == false && DigitosMaxAlcanzados("0") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + 0);
    }//GEN-LAST:event_ceroMousePressed

    private void puntoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puntoMousePressed
        if (MontoMaximaAlcanzado(".") == false && DigitosMaxAlcanzados(".") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + ".");
    }//GEN-LAST:event_puntoMousePressed

    private void dobleCeroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobleCeroMousePressed
        if (MontoMaximaAlcanzado("00") == false && DigitosMaxAlcanzados("00") == false)
            jblMontoDeposito.setText(jblMontoDeposito.getText() + "00");
    }//GEN-LAST:event_dobleCeroMousePressed

    private void cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMousePressed
        jblMontoDeposito.setText("");
    }//GEN-LAST:event_cancelarMousePressed

    private void correccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correccionMousePressed

        if (jblMontoDeposito.getText().length() > 0) {
            String nuevoTexto = "";
            for (int i = 0; i < jblMontoDeposito.getText().length() - 1; i++) {
                nuevoTexto = nuevoTexto + jblMontoDeposito.getText().charAt(i);
            }
            jblMontoDeposito.setText(nuevoTexto);
        }
    }//GEN-LAST:event_correccionMousePressed

    private void aceptarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMousePressed
        boolean montoValido = false;
        double monto = 0.0;
        try {
            monto = Double.parseDouble(jblMontoDeposito.getText());
            montoValido = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el monto ingresado");
        }

        if (montoValido == true) {
            int eleccion = JOptionPane.showConfirmDialog(null, "Deseas realizar el deposito?", "Elije una opcion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (eleccion == 0) {
                for (Usuarios i : SedeCentral.getListaUsers()) {
                    if (i.getCedula().equals(this.cedula)) {
                        switch (this.cuentaElegida) {
                            case "corriente" -> {
                                i.getCuentaCorriente().depositarDinero(monto);
                            }
                            case "ahorro" -> {
                                i.getCuentaAhorro().depositarDinero(monto);
                            }
                            case "simpe" -> {
                                i.getCuentaSimpe().depositarDinero(monto);
                            }
                        }
                        JOptionPane.showMessageDialog(null, "Deposito realizado exitosamente");
                        jblMontoDeposito.setText("");
                        pizarra.setSelectedIndex(0);
                        txtsPorDefecto();
                    }
                }
            }
        }
    }//GEN-LAST:event_aceptarMousePressed

    private void jblSimpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaSimpe().getEstado() == true) {
                    Simpe simpe = new Simpe(this.cedula, this.sede);
                    simpe.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Cuenta simpe inactiva, debes habilitarla");
                }
            }
        }
    }//GEN-LAST:event_jblSimpeMouseClicked

    private void jblSimpeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseEntered
        panelSimpeBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblSimpeMouseEntered

    private void jblSimpeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseExited
        panelSimpeBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblSimpeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Depositar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aceptar;
    private javax.swing.JLabel alertaClave;
    private javax.swing.JPanel background;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel cero;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel correccion;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel dobleCero;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel iconBarra;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblAlerta;
    private javax.swing.JLabel jblAtras;
    private javax.swing.JLabel jblBarra;
    private javax.swing.JLabel jblClaveNum;
    private javax.swing.JLabel jblComentarios;
    private javax.swing.JLabel jblConfig;
    private javax.swing.JLabel jblContinuar;
    private javax.swing.JLabel jblCuentaAhorro;
    private javax.swing.JLabel jblCuentaCorriente;
    private javax.swing.JLabel jblCuentaSimpe;
    private javax.swing.JLabel jblDashboard;
    private javax.swing.JLabel jblDepositar;
    private javax.swing.JLabel jblFondoPerfil;
    private javax.swing.JLabel jblHabilitarCuentas;
    private javax.swing.JLabel jblInformativo;
    private javax.swing.JLabel jblInformativoDep;
    private javax.swing.JLabel jblMontoDeposito;
    private javax.swing.JLabel jblNombreBanco;
    private javax.swing.JLabel jblNombrePerfil;
    private javax.swing.JLabel jblOpcionActual;
    private javax.swing.JLabel jblOpcionActual1;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblPerfil;
    private javax.swing.JLabel jblRetirar;
    private javax.swing.JLabel jblSalir;
    private javax.swing.JLabel jblSimpe;
    private javax.swing.JLabel jblVentanaActual;
    private javax.swing.JLabel jblVerPassword;
    private javax.swing.JLabel nueve;
    private javax.swing.JLabel ocho;
    private javax.swing.JPanel panelAceptar;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelCancelar;
    private javax.swing.JPanel panelComentariosBarra;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelContinuar;
    private javax.swing.JPanel panelCorreccion;
    private javax.swing.JPanel panelCuentaAhorro;
    private javax.swing.JPanel panelCuentaCorriente;
    private javax.swing.JPanel panelCuentaSimpe;
    private javax.swing.JPanel panelDashboardBarra;
    private javax.swing.JPanel panelDepositarBarra;
    private javax.swing.JPanel panelDeposito;
    private javax.swing.JPanel panelElegir;
    private javax.swing.JPanel panelHabilitarCuentasBarra;
    private javax.swing.JPanel panelMontoDeposito;
    private javax.swing.JPanel panelNum0;
    private javax.swing.JPanel panelNum00;
    private javax.swing.JPanel panelNum1;
    private javax.swing.JPanel panelNum2;
    private javax.swing.JPanel panelNum3;
    private javax.swing.JPanel panelNum4;
    private javax.swing.JPanel panelNum5;
    private javax.swing.JPanel panelNum6;
    private javax.swing.JPanel panelNum7;
    private javax.swing.JPanel panelNum8;
    private javax.swing.JPanel panelNum9;
    private javax.swing.JPanel panelNumerico;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPunto;
    private javax.swing.JPanel panelRetirarBarra;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelSimpeBarra;
    private javax.swing.JPanel panelValidar;
    private javax.swing.JPanel panelVerPassword;
    private javax.swing.JPanel panelVerSaldoBarra;
    private javax.swing.JTabbedPane pizarra;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JLabel punto;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel tocar;
    private javax.swing.JLabel tres;
    private javax.swing.JTextField txtClaveNum;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
