package guiUsuarios;

import Personas.Usuarios;
import Sedes.SedeCentral;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class HabilitarCuentas extends javax.swing.JFrame {

    String cedula;
    int sede;
    boolean verPassword;

    public HabilitarCuentas(String cedula, int sede) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cedula = cedula;
        this.sede = sede;
        this.verPassword = false;
        panelHabilitarCuentasBarra.setBackground(new Color(232, 225, 182));
        alertaClave.setVisible(false);
        jblAlerta.setVisible(false);
        txtsPorDefecto();

        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                jblNombrePerfil.setText(i.getUsuario() + " " + i.getApellidos());
                switch (this.sede) {
                    case 0 -> {
                        jblVentanaActual.setText("Sede Puriscal");
                    }
                    case 1 -> {
                        jblVentanaActual.setText("Sede San Pedro");
                    }
                    case 2 -> {
                        jblVentanaActual.setText("Sede Ciudad Colon");
                    }
                }
            }
        }
    }

    public HabilitarCuentas() {
        initComponents();
    }

    public void txtsPorDefecto() {
        txtClaveNum.setText("Ingrese su clave");
        psdPassword.setText("Ingrese su password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jblNombreBanco = new javax.swing.JLabel();
        jblPerfil = new javax.swing.JLabel();
        iconBarra = new javax.swing.JLabel();
        jblNombrePerfil = new javax.swing.JLabel();
        jblVentanaActual = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        jblAtras = new javax.swing.JLabel();
        jblBarra = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        jblSalir = new javax.swing.JLabel();
        panelConfig = new javax.swing.JPanel();
        jblConfig = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        jblFondoPerfil = new javax.swing.JLabel();
        panelDepositarBarra = new javax.swing.JPanel();
        jblDepositar = new javax.swing.JLabel();
        panelRetirarBarra = new javax.swing.JPanel();
        jblRetirar = new javax.swing.JLabel();
        panelVerSaldoBarra = new javax.swing.JPanel();
        javax.swing.JLabel jblVerSaldo = new javax.swing.JLabel();
        panelDashboardBarra = new javax.swing.JPanel();
        jblDashboard = new javax.swing.JLabel();
        panelHabilitarCuentasBarra = new javax.swing.JPanel();
        jblHabilitarCuentas = new javax.swing.JLabel();
        panelComentariosBarra = new javax.swing.JPanel();
        jblComentarios = new javax.swing.JLabel();
        panelSimpeBarra = new javax.swing.JPanel();
        jblSimpe = new javax.swing.JLabel();
        pizarra = new javax.swing.JTabbedPane();
        panelValidar = new javax.swing.JPanel();
        jblClaveNum = new javax.swing.JLabel();
        txtClaveNum = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jblPassword = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        panelVerPassword = new javax.swing.JPanel();
        jblVerPassword = new javax.swing.JLabel();
        panelContinuar = new javax.swing.JPanel();
        jblContinuar = new javax.swing.JLabel();
        alertaClave = new javax.swing.JLabel();
        jblAlerta = new javax.swing.JLabel();
        jblOpcionActual = new javax.swing.JLabel();
        panelElegir = new javax.swing.JPanel();
        jblOpcionActual1 = new javax.swing.JLabel();
        panelCuentaAhorro = new javax.swing.JPanel();
        jblCuentaAhorro = new javax.swing.JLabel();
        panelCuentaSimpe = new javax.swing.JPanel();
        jblCuentaSimpe = new javax.swing.JLabel();
        jblInformativo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblNombreBanco.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblNombreBanco.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco.setText("BNBUU");
        background.add(jblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 120, 70));

        jblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfilNegro128px.png"))); // NOI18N
        background.add(jblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 130, 130));

        iconBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo32px.png"))); // NOI18N
        background.add(iconBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 70));

        jblNombrePerfil.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jblNombrePerfil.setForeground(new java.awt.Color(51, 51, 51));
        jblNombrePerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombrePerfil.setText("Nombre");
        background.add(jblNombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, -1));

        jblVentanaActual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblVentanaActual.setForeground(new java.awt.Color(51, 51, 51));
        jblVentanaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubicacion32px.png"))); // NOI18N
        jblVentanaActual.setText("Ubicacion");
        background.add(jblVentanaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 320, 70));

        panelAtras.setBackground(new java.awt.Color(210, 196, 103));
        panelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblAtrasMouseExited(evt);
            }
        });
        panelAtras.add(jblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 50, 50));

        jblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BarraColorBambu.png"))); // NOI18N
        background.add(jblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 790, 70));

        panelSalir.setBackground(new java.awt.Color(247, 240, 194));
        panelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida32px.png"))); // NOI18N
        jblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblSalirMouseExited(evt);
            }
        });
        panelSalir.add(jblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        panelConfig.setBackground(new java.awt.Color(247, 240, 194));
        panelConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config32px.png"))); // NOI18N
        jblConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblConfigMouseExited(evt);
            }
        });
        panelConfig.add(jblConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        background.add(panelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 50, 50));

        panelOpciones.setBackground(new java.awt.Color(252, 247, 215));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblFondoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFondoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CuadroFondoPerfil2.png"))); // NOI18N
        panelOpciones.add(jblFondoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        panelDepositarBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelDepositarBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDepositar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDepositar.setForeground(new java.awt.Color(102, 102, 102));
        jblDepositar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDepositar.setText("Depositar");
        jblDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDepositarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDepositarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDepositarMouseExited(evt);
            }
        });
        panelDepositarBarra.add(jblDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelDepositarBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 60));

        panelRetirarBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelRetirarBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblRetirar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblRetirar.setForeground(new java.awt.Color(102, 102, 102));
        jblRetirar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblRetirar.setText("Retirar");
        jblRetirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblRetirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblRetirarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblRetirarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblRetirarMouseExited(evt);
            }
        });
        panelRetirarBarra.add(jblRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelRetirarBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 60));

        panelVerSaldoBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelVerSaldoBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblVerSaldo.setForeground(new java.awt.Color(102, 102, 102));
        jblVerSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerSaldo.setText("Ver saldo");
        jblVerSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerSaldoMouseExited(evt);
            }
        });
        panelVerSaldoBarra.add(jblVerSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelVerSaldoBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 60));

        panelDashboardBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelDashboardBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDashboard.setForeground(new java.awt.Color(102, 102, 102));
        jblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDashboard.setText("Dashboard");
        jblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDashboardMouseExited(evt);
            }
        });
        panelDashboardBarra.add(jblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelDashboardBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 60));

        panelHabilitarCuentasBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelHabilitarCuentasBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblHabilitarCuentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblHabilitarCuentas.setForeground(new java.awt.Color(102, 102, 102));
        jblHabilitarCuentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblHabilitarCuentas.setText("Habilitar Cuentas");
        jblHabilitarCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblHabilitarCuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblHabilitarCuentasMouseExited(evt);
            }
        });
        panelHabilitarCuentasBarra.add(jblHabilitarCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelHabilitarCuentasBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 60));

        panelComentariosBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelComentariosBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblComentarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblComentarios.setForeground(new java.awt.Color(102, 102, 102));
        jblComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblComentarios.setText("Comentarios");
        jblComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblComentariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblComentariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblComentariosMouseExited(evt);
            }
        });
        panelComentariosBarra.add(jblComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelComentariosBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 300, 60));

        panelSimpeBarra.setBackground(new java.awt.Color(252, 247, 215));
        panelSimpeBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblSimpe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblSimpe.setForeground(new java.awt.Color(102, 102, 102));
        jblSimpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSimpe.setText("Simpe");
        jblSimpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblSimpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSimpeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblSimpeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblSimpeMouseExited(evt);
            }
        });
        panelSimpeBarra.add(jblSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panelOpciones.add(panelSimpeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 60));

        background.add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        pizarra.setBackground(new java.awt.Color(204, 204, 204));
        pizarra.setForeground(new java.awt.Color(102, 102, 102));

        panelValidar.setBackground(new java.awt.Color(255, 255, 255));
        panelValidar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblClaveNum.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblClaveNum.setForeground(new java.awt.Color(51, 51, 51));
        jblClaveNum.setText("CLAVE NUMERICA");
        panelValidar.add(jblClaveNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtClaveNum.setBackground(new java.awt.Color(255, 255, 255));
        txtClaveNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtClaveNum.setForeground(new java.awt.Color(204, 204, 204));
        txtClaveNum.setText("Ingrese su clave");
        txtClaveNum.setBorder(null);
        txtClaveNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtClaveNumMousePressed(evt);
            }
        });
        txtClaveNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtClaveNumKeyTyped(evt);
            }
        });
        panelValidar.add(txtClaveNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, 50));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        panelValidar.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 530, 10));

        jblPassword.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        panelValidar.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("Ingrese su password");
        psdPassword.setBorder(null);
        psdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordMousePressed(evt);
            }
        });
        panelValidar.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 380, 60));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        panelValidar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 530, 10));

        panelVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseExited(evt);
            }
        });
        panelVerPassword.add(jblVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelValidar.add(panelVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 40, 40));

        panelContinuar.setBackground(new java.awt.Color(92, 88, 29));
        panelContinuar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblContinuar.setBackground(new java.awt.Color(92, 88, 29));
        jblContinuar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblContinuar.setText("CONTINUAR");
        jblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblContinuarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblContinuarMouseExited(evt);
            }
        });
        panelContinuar.add(jblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        panelValidar.add(panelContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 170, 70));

        alertaClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertaClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/advertencia.png"))); // NOI18N
        panelValidar.add(alertaClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 40, 40));

        jblAlerta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblAlerta.setForeground(new java.awt.Color(255, 102, 102));
        jblAlerta.setText("Solo numeros");
        panelValidar.add(jblAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 185, 250, -1));

        jblOpcionActual.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblOpcionActual.setForeground(new java.awt.Color(51, 51, 51));
        jblOpcionActual.setText("HABILITAR CUENTA");
        panelValidar.add(jblOpcionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 360, 40));

        pizarra.addTab("Validar", panelValidar);

        panelElegir.setBackground(new java.awt.Color(255, 255, 255));
        panelElegir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblOpcionActual1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblOpcionActual1.setForeground(new java.awt.Color(51, 51, 51));
        jblOpcionActual1.setText("HABILITAR CUENTA");
        panelElegir.add(jblOpcionActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 360, 40));

        panelCuentaAhorro.setBackground(new java.awt.Color(92, 88, 29));
        panelCuentaAhorro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCuentaAhorro.setBackground(new java.awt.Color(0, 0, 0));
        jblCuentaAhorro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblCuentaAhorro.setForeground(new java.awt.Color(255, 255, 255));
        jblCuentaAhorro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCuentaAhorro.setText("Cuenta ahorro");
        jblCuentaAhorro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblCuentaAhorro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblCuentaAhorroMouseExited(evt);
            }
        });
        panelCuentaAhorro.add(jblCuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        panelElegir.add(panelCuentaAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 460, 70));

        panelCuentaSimpe.setBackground(new java.awt.Color(92, 88, 29));
        panelCuentaSimpe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblCuentaSimpe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblCuentaSimpe.setForeground(new java.awt.Color(255, 255, 255));
        jblCuentaSimpe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblCuentaSimpe.setText("Cuenta simpe");
        jblCuentaSimpe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblCuentaSimpe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblCuentaSimpeMouseExited(evt);
            }
        });
        panelCuentaSimpe.add(jblCuentaSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 70));

        panelElegir.add(panelCuentaSimpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 460, 70));

        jblInformativo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jblInformativo.setForeground(new java.awt.Color(51, 51, 51));
        jblInformativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblInformativo.setText("Elige la cuenta para habilitar");
        panelElegir.add(jblInformativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 550, 60));

        pizarra.addTab("Elegir", panelElegir);

        background.add(pizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 790, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseClicked
        switch (pizarra.getSelectedIndex()) {
            case 0 -> {
                PrincipalUsers users = new PrincipalUsers(this.cedula, this.sede);
                users.setVisible(true);
                panelVerSaldoBarra.setBackground(new Color(252, 247, 215));
                this.dispose();
            }
            case 1 -> {
                pizarra.setSelectedIndex(0);
                txtsPorDefecto();
            }
        }
    }//GEN-LAST:event_jblAtrasMouseClicked

    private void jblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseEntered
        panelAtras.setBackground(new Color(245, 228, 120));
    }//GEN-LAST:event_jblAtrasMouseEntered

    private void jblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseExited
        panelAtras.setBackground(new Color(210, 196, 103));
    }//GEN-LAST:event_jblAtrasMouseExited

    private void jblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseClicked
        Inicio ini = new Inicio();
        ini.setVisible(true);
        panelVerSaldoBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblSalirMouseClicked

    private void jblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseEntered
        panelSalir.setBackground(new Color(255, 255, 218));
    }//GEN-LAST:event_jblSalirMouseEntered

    private void jblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseExited
        panelSalir.setBackground(new Color(247, 240, 194));
    }//GEN-LAST:event_jblSalirMouseExited

    private void jblConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseClicked
        ConfigurarPerfil config = new ConfigurarPerfil(this.cedula, this.sede);
        config.setVisible(true);
        panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblConfigMouseClicked

    private void jblConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseEntered
        panelConfig.setBackground(new Color(255, 255, 218));
    }//GEN-LAST:event_jblConfigMouseEntered

    private void jblConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseExited
        panelConfig.setBackground(new Color(247, 240, 194));
    }//GEN-LAST:event_jblConfigMouseExited

    private void jblDepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseClicked
        Depositar depositar = new Depositar(this.cedula, this.sede);
        depositar.setVisible(true);
        panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblDepositarMouseClicked

    private void jblDepositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseEntered
        panelDepositarBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDepositarMouseEntered

    private void jblDepositarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseExited
        panelDepositarBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDepositarMouseExited

    private void jblRetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseClicked
        Retirar retirar = new Retirar(this.cedula, this.sede);
        retirar.setVisible(true);
        panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblRetirarMouseClicked

    private void jblRetirarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseEntered
        panelRetirarBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblRetirarMouseEntered

    private void jblRetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRetirarMouseExited
        panelRetirarBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblRetirarMouseExited

    private void jblVerSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseClicked
        VerSaldo ver = new VerSaldo(this.cedula, this.sede);
        ver.setVisible(true);
        panelRetirarBarra.setBackground(new Color(252, 247, 215));
        this.dispose(); 
    }//GEN-LAST:event_jblVerSaldoMouseClicked

    private void jblVerSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseEntered
        panelVerSaldoBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblVerSaldoMouseEntered

    private void jblVerSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerSaldoMouseExited
        panelVerSaldoBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblVerSaldoMouseExited

    private void jblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseClicked
        PrincipalUsers users = new PrincipalUsers(this.cedula, this.sede);
        users.setVisible(true);
        panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
        this.dispose();
    }//GEN-LAST:event_jblDashboardMouseClicked

    private void jblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseEntered
        panelDashboardBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDashboardMouseEntered

    private void jblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseExited
        panelDashboardBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDashboardMouseExited

    private void jblHabilitarCuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseClicked

    }//GEN-LAST:event_jblHabilitarCuentasMouseClicked

    private void jblHabilitarCuentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseEntered
        //panelHabilitarCuentasBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblHabilitarCuentasMouseEntered

    private void jblHabilitarCuentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblHabilitarCuentasMouseExited
        //panelHabilitarCuentasBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblHabilitarCuentasMouseExited

    private void jblComentariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseClicked

    }//GEN-LAST:event_jblComentariosMouseClicked

    private void jblComentariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseEntered
        panelComentariosBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblComentariosMouseEntered

    private void jblComentariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblComentariosMouseExited
        panelComentariosBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblComentariosMouseExited

    private void txtClaveNumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClaveNumMousePressed

        String psd = String.valueOf(psdPassword.getPassword());
        if (txtClaveNum.getText().equals("Ingrese su clave")) {
            txtClaveNum.setText("");
        }
        txtClaveNum.setForeground(Color.black);
        if (psd.equals("")) {
            psdPassword.setText("Ingrese su password");
        } else {
            psdPassword.setText(psd);
        }
        psdPassword.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_txtClaveNumMousePressed

    private void txtClaveNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClaveNumKeyTyped
        char tecla = evt.getKeyChar();
        boolean teclaBorrar = true;
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            teclaBorrar = false;
        }

        if (!Character.isDigit(tecla) && teclaBorrar == false) {

            evt.consume();
            alertaClave.setVisible(true);
            jblAlerta.setVisible(true);
            jblAlerta.setText("Solo numeros");

        } else if (txtClaveNum.getText().length() == 4) {
            evt.consume();
            jblAlerta.setText("Max numeros alcanzado");
            jblAlerta.setVisible(true);
            alertaClave.setVisible(true);
        } else {
            alertaClave.setVisible(false);
            jblAlerta.setVisible(false);
        }
    }//GEN-LAST:event_txtClaveNumKeyTyped

    private void psdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordMousePressed

        String user = txtClaveNum.getText();
        if (String.valueOf(psdPassword.getPassword()).equals("Ingrese su password")) {
            psdPassword.setText("");
        }
        psdPassword.setForeground(Color.black);
        if (user.equals("")) {
            txtClaveNum.setText("Ingrese su clave");
        } else {
            txtClaveNum.setText(user);
        }
        txtClaveNum.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_psdPasswordMousePressed

    private void jblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseClicked
        if (verPassword == false) {
            verPassword = true;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');

        }
    }//GEN-LAST:event_jblVerPasswordMouseClicked

    private void jblVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseEntered
        panelVerPassword.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPasswordMouseEntered

    private void jblVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseExited
        panelVerPassword.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPasswordMouseExited

    private void jblContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseClicked
        try {
            for (Usuarios i : SedeCentral.ListaUsers) {
                if (i.getCedula().equals(this.cedula)) {
                    if (Integer.parseInt(txtClaveNum.getText()) == i.getClaveNumerica() && String.valueOf(psdPassword.getPassword()).equals(i.getPassword())) {
                        JOptionPane.showMessageDialog(null, "Datos correctos");
                        pizarra.setSelectedIndex(1);
                    } else {
                        JOptionPane.showMessageDialog(null, "Datos incorrectos");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Rellena todos los espacios");
        }
    }//GEN-LAST:event_jblContinuarMouseClicked

    private void jblContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseEntered
        panelContinuar.setBackground(new Color(153, 145, 86));
        jblContinuar.setForeground(Color.black);
    }//GEN-LAST:event_jblContinuarMouseEntered

    private void jblContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblContinuarMouseExited
        panelContinuar.setBackground(new Color(92, 88, 29));
        jblContinuar.setForeground(Color.white);
    }//GEN-LAST:event_jblContinuarMouseExited

    private void jblCuentaAhorroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaAhorro().getEstado() == false) {
                    int eleccion = JOptionPane.showConfirmDialog(null, "Deseas habilitar la cuenta de ahorro?", "HABILITAR CUENTA", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(eleccion == 0){
                        i.getCuentaAhorro().setEstado(true);
                        JOptionPane.showMessageDialog(null, "Cuenta de ahorro habilitada para: "+i.getUsuario());
                        pizarra.setSelectedIndex(0);
                        txtsPorDefecto();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La cuenta ya esta habilitada");
                }
            }
        }
    }//GEN-LAST:event_jblCuentaAhorroMouseClicked

    private void jblCuentaAhorroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseEntered
        panelCuentaAhorro.setBackground(new Color(153, 145, 86));
        jblCuentaAhorro.setForeground(Color.black);
    }//GEN-LAST:event_jblCuentaAhorroMouseEntered

    private void jblCuentaAhorroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaAhorroMouseExited
        panelCuentaAhorro.setBackground(new Color(92, 88, 29));
        jblCuentaAhorro.setForeground(Color.white);
    }//GEN-LAST:event_jblCuentaAhorroMouseExited

    private void jblCuentaSimpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaSimpe().getEstado() == false) {
                    int eleccion = JOptionPane.showConfirmDialog(null, "Deseas habilitar la cuenta de simpe?", "HABILITAR CUENTA", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(eleccion == 0){
                        i.getCuentaSimpe().setEstado(true);
                        JOptionPane.showMessageDialog(null, "Cuenta de simpe habilitada para: "+i.getUsuario());
                        pizarra.setSelectedIndex(0);
                        txtsPorDefecto();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La cuenta ya esta habilitada");
                }
            }
        }
    }//GEN-LAST:event_jblCuentaSimpeMouseClicked

    private void jblCuentaSimpeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseEntered
        panelCuentaSimpe.setBackground(new Color(153, 145, 86));
        jblCuentaSimpe.setForeground(Color.black);
    }//GEN-LAST:event_jblCuentaSimpeMouseEntered

    private void jblCuentaSimpeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblCuentaSimpeMouseExited
        panelCuentaSimpe.setBackground(new Color(92, 88, 29));
        jblCuentaSimpe.setForeground(Color.white);
    }//GEN-LAST:event_jblCuentaSimpeMouseExited

    private void jblSimpeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseClicked
        for (Usuarios i : SedeCentral.getListaUsers()) {
            if (i.getCedula().equals(this.cedula)) {
                if (i.getCuentaSimpe().getEstado() == true) {
                    Simpe simpe = new Simpe(this.cedula, this.sede);
                    simpe.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Cuenta simpe inactiva, debes habilitarla");
                }
            }
        }
    }//GEN-LAST:event_jblSimpeMouseClicked

    private void jblSimpeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseEntered
        panelSimpeBarra.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblSimpeMouseEntered

    private void jblSimpeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSimpeMouseExited
        panelSimpeBarra.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblSimpeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabilitarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabilitarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabilitarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabilitarCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabilitarCuentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertaClave;
    private javax.swing.JPanel background;
    private javax.swing.JLabel iconBarra;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblAlerta;
    private javax.swing.JLabel jblAtras;
    private javax.swing.JLabel jblBarra;
    private javax.swing.JLabel jblClaveNum;
    private javax.swing.JLabel jblComentarios;
    private javax.swing.JLabel jblConfig;
    private javax.swing.JLabel jblContinuar;
    private javax.swing.JLabel jblCuentaAhorro;
    private javax.swing.JLabel jblCuentaSimpe;
    private javax.swing.JLabel jblDashboard;
    private javax.swing.JLabel jblDepositar;
    private javax.swing.JLabel jblFondoPerfil;
    private javax.swing.JLabel jblHabilitarCuentas;
    private javax.swing.JLabel jblInformativo;
    private javax.swing.JLabel jblNombreBanco;
    private javax.swing.JLabel jblNombrePerfil;
    private javax.swing.JLabel jblOpcionActual;
    private javax.swing.JLabel jblOpcionActual1;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblPerfil;
    private javax.swing.JLabel jblRetirar;
    private javax.swing.JLabel jblSalir;
    private javax.swing.JLabel jblSimpe;
    private javax.swing.JLabel jblVentanaActual;
    private javax.swing.JLabel jblVerPassword;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelComentariosBarra;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelContinuar;
    private javax.swing.JPanel panelCuentaAhorro;
    private javax.swing.JPanel panelCuentaSimpe;
    private javax.swing.JPanel panelDashboardBarra;
    private javax.swing.JPanel panelDepositarBarra;
    private javax.swing.JPanel panelElegir;
    private javax.swing.JPanel panelHabilitarCuentasBarra;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelRetirarBarra;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelSimpeBarra;
    private javax.swing.JPanel panelValidar;
    private javax.swing.JPanel panelVerPassword;
    private javax.swing.JPanel panelVerSaldoBarra;
    private javax.swing.JTabbedPane pizarra;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JTextField txtClaveNum;
    // End of variables declaration//GEN-END:variables
}
