package gui;

import ClasesProyecto.Datos;
import ClasesProyecto.Personas;
import Personas.Administradores;
import Personas.Usuarios;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    boolean verPassword = false;
    int index;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtsPorDefecto();
    }

    public void txtsPorDefecto() {
        txtUsuario.setText("Ingrese su usuario");
        psdPassword.setText("Ingrese su password");
        cbRol.setSelectedIndex(0);
    }

    public void validarDatosUsuarios(int listaUsuarios) {
        boolean CredencialesIguales = false;
        String usuario = txtUsuario.getText();
        String password = String.valueOf(psdPassword.getPassword());
        
        try {
            if (listaUsuarios > 0) {

                for (Usuarios p : Datos.listaUsuarios) {
                    if (p.getUsuario().equals(usuario) && p.getPassword().equals(password)) {
                        CredencialesIguales = true;
                        index = Datos.listaUsuarios.indexOf(p);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay usuarios registrados");
                txtsPorDefecto();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, intentalo de nuevo");
            txtsPorDefecto();
        }

        if (CredencialesIguales == true) {
            JOptionPane.showMessageDialog(null, "Datos correctos");
            Datos.setIndiceLogin(index);
            PrincipalUsers users = new PrincipalUsers();
            users.setVisible(true);
            this.dispose();

        } else if (listaUsuarios > 0 && CredencialesIguales == false) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            txtsPorDefecto();
        }
    }
    public void validarDatosAdmins(int listaAdmins) {
        boolean CredencialesIguales = false;
        String usuario = txtUsuario.getText();
        String password = String.valueOf(psdPassword.getPassword());
        
        try {
            if (listaAdmins > 0) {

                for (Administradores p : Datos.listaAdmins) {
                    if (p.getUsuario().equals(usuario) && p.getPassword().equals(password)) {
                        CredencialesIguales = true;
                        index = Datos.listaAdmins.indexOf(p);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay administradores registrados");
                txtsPorDefecto();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, intentalo de nuevo");
            txtsPorDefecto();
        }

        if (CredencialesIguales == true) {
            JOptionPane.showMessageDialog(null, "Datos correctos");
            Datos.setIndiceLogin(index);
            PrincipalAdmins admins = new PrincipalAdmins();
            admins.setVisible(true);
            this.dispose();

        } else if (listaAdmins > 0 && CredencialesIguales == false) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            txtsPorDefecto();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        backgroundLogin = new javax.swing.JPanel();
        panelAtras = new javax.swing.JPanel();
        jblAtras = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jblRolOF = new javax.swing.JLabel();
        jblBarraArriba = new javax.swing.JLabel();
        jblLogo = new javax.swing.JLabel();
        jblNombreBanco = new javax.swing.JLabel();
        jblFrase = new javax.swing.JLabel();
        jblFondoPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jblUsuario = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        panelEntrar = new javax.swing.JPanel();
        jblEntrar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jblIniciarSesion = new javax.swing.JLabel();
        panelnAtras = new javax.swing.JPanel();
        panelVerPassword = new javax.swing.JPanel();
        jblVerPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundLogin.setBackground(new java.awt.Color(255, 255, 255));
        backgroundLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAtras.setBackground(new java.awt.Color(252, 247, 215));
        panelAtras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblAtrasMouseExited(evt);
            }
        });
        panelAtras.add(jblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        backgroundLogin.add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        cbRol.setBackground(new java.awt.Color(255, 255, 255));
        cbRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbRol.setForeground(new java.awt.Color(153, 153, 153));
        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Admin" }));
        cbRol.setBorder(null);
        cbRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbRolMousePressed(evt);
            }
        });
        backgroundLogin.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 140, 30));

        jblRolOF.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblRolOF.setForeground(new java.awt.Color(51, 51, 51));
        jblRolOF.setText("ROL");
        backgroundLogin.add(jblRolOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 90, 30));

        jblBarraArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BarraInicio.png"))); // NOI18N
        backgroundLogin.add(jblBarraArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo128px.png"))); // NOI18N
        backgroundLogin.add(jblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 390, 130));

        jblNombreBanco.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jblNombreBanco.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreBanco.setText("BNBUU");
        backgroundLogin.add(jblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 390, -1));

        jblFrase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFrase.setForeground(new java.awt.Color(51, 51, 51));
        jblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFrase.setText("Deje que su dinero brote con nosotros");
        backgroundLogin.add(jblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 390, -1));

        jblFondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        backgroundLogin.add(jblFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 390, 680));

        jLabel1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo64px.png"))); // NOI18N
        jLabel1.setText("BNBUU");
        backgroundLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 205, -1));

        jblPassword.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        backgroundLogin.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        backgroundLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 420, 50));

        jblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jblUsuario.setText("USUARIO");
        backgroundLogin.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("Ingrese su password");
        psdPassword.setBorder(null);
        psdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordMousePressed(evt);
            }
        });
        backgroundLogin.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 380, 60));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        backgroundLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 530, 10));

        panelEntrar.setBackground(new java.awt.Color(92, 88, 29));
        panelEntrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblEntrar.setBackground(new java.awt.Color(92, 88, 29));
        jblEntrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblEntrar.setText("ENTRAR");
        jblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblEntrarMouseExited(evt);
            }
        });
        panelEntrar.add(jblEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 70));

        backgroundLogin.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 560, 170, 70));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        backgroundLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 530, 10));

        jblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jblIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        jblIniciarSesion.setText("INICIAR SESION");
        backgroundLogin.add(jblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelnAtras.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelnAtrasLayout = new javax.swing.GroupLayout(panelnAtras);
        panelnAtras.setLayout(panelnAtrasLayout);
        panelnAtrasLayout.setHorizontalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelnAtrasLayout.setVerticalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        backgroundLogin.add(panelnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        panelVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseExited(evt);
            }
        });
        panelVerPassword.add(jblVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        backgroundLogin.add(panelVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 40, 40));

        panelLogin.add(backgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, -1, 690));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed

        String psd = String.valueOf(psdPassword.getPassword());
        if (txtUsuario.getText().equals("Ingrese su usuario")) {
            txtUsuario.setText("");
        }
        txtUsuario.setForeground(Color.black);
        if (psd.equals("")) {
            psdPassword.setText("Ingrese su password");
        } else {
            psdPassword.setText(psd);
        }
        psdPassword.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void psdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordMousePressed

        String user = txtUsuario.getText();
        if (String.valueOf(psdPassword.getPassword()).equals("Ingrese su password")) {
            psdPassword.setText("");
        }
        psdPassword.setForeground(Color.black);
        if (user.equals("")) {
            txtUsuario.setText("Ingrese su usuario");
        } else {
            txtUsuario.setText(user);
        }
        txtUsuario.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_psdPasswordMousePressed

    private void jblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseClicked
        
        int rol = cbRol.getSelectedIndex();
        int personasRegistradas;
        
        if (rol == 0) {
            personasRegistradas = Datos.listaUsuarios.size();
            validarDatosUsuarios(personasRegistradas);
        } else {
            personasRegistradas = Datos.listaAdmins.size();
            validarDatosAdmins(personasRegistradas);
        }  
    }//GEN-LAST:event_jblEntrarMouseClicked

    private void jblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseEntered
        panelEntrar.setBackground(new Color(153, 145, 86));
        jblEntrar.setForeground(Color.black);
    }//GEN-LAST:event_jblEntrarMouseEntered

    private void jblEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseExited
        panelEntrar.setBackground(new Color(92, 88, 29));
        jblEntrar.setForeground(Color.white);
    }//GEN-LAST:event_jblEntrarMouseExited

    private void jblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseClicked
        if (verPassword == false) {
            verPassword = true;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');

        }
    }//GEN-LAST:event_jblVerPasswordMouseClicked

    private void jblVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseEntered
        panelVerPassword.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPasswordMouseEntered

    private void jblVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseExited
        panelVerPassword.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPasswordMouseExited

    private void jblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseClicked
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jblAtrasMouseClicked

    private void jblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseEntered
        panelAtras.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblAtrasMouseEntered

    private void jblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseExited
        panelAtras.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblAtrasMouseExited

    private void cbRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRolMousePressed

        cbRol.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_cbRolMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundLogin;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblAtras;
    private javax.swing.JLabel jblBarraArriba;
    private javax.swing.JLabel jblEntrar;
    private javax.swing.JLabel jblFondoPanel;
    private javax.swing.JLabel jblFrase;
    private javax.swing.JLabel jblIniciarSesion;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblNombreBanco;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblRolOF;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JLabel jblVerPassword;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelVerPassword;
    private javax.swing.JPanel panelnAtras;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
